# Assignment B2

Problem Statement: Classify the email using the binary classification method. Email Spam detection has two
states: a) Normal State Not Spam, b) Abnormal State Spam. Use K-Nearest Neighbors 
and Support Vector Machine for classification. Analyze their performance

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

## Dataset Description:
The csv file contains 5172 rows, each row for each email. There are 3002 columns. The first column indicates Email name. The name has been set with numbers and not recipients' name to protect privacy. The last column has the labels for prediction : 1 for spam, 0 for not spam. The remaining 3000 columns are the 3000 most common words in all the emails, after excluding the non-alphabetical characters/words.

In [2]:
df = pd.read_csv("emails.csv")
df.head()

Email No.  the  to  ect  and  for  of    a  you  hou  ...  connevey  jay  \
0   Email 1    0   0    1    0    0   0    2    0    0  ...         0    0   
1   Email 2    8  13   24    6    6   2  102    1   27  ...         0    0   
2   Email 3    0   0    1    0    0   0    8    0    0  ...         0    0   
3   Email 4    0   5   22    0    5   1   51    2   10  ...         0    0   
4   Email 5    7   6   17    1    5   2   57    0    9  ...         0    0   

   valued  lay  infrastructure  military  allowing  ff  dry  Prediction  
0       0    0               0         0         0   0    0           0  
1       0    0               0         0         0   1    0           0  
2       0    0               0         0         0   0    0           0  
3       0    0               0         0         0   0    0           0  
4       0    0               0         0         0   1    0           0  

[5 rows x 3002 columns]

## K Nearest Neighbours

In [9]:
x = df.iloc[:,1:3001]
y = df.iloc[:,-1]

In [10]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=.2 ,random_state=12)

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [12]:
from sklearn.neighbors import KNeighborsClassifier  
knn= KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2)  
knn.fit(x_train, y_train) 

KNeighborsClassifier()

In [13]:
y_pred_knn = knn.predict(x_test)
y_pred_knn

array([1, 0, 0, ..., 1, 1, 1], dtype=int64)

In [14]:
cm = confusion_matrix(y_test, y_pred_knn)
cm

array([[586, 113],
       [ 24, 312]], dtype=int64)

In [22]:
print("Accuracy:",accuracy_score(y_test, y_pred_knn))
print("Precision:",precision_score(y_test, y_pred_knn))
print("Recall:",recall_score(y_test, y_pred_knn))
print("F1:",f1_score(y_test, y_pred_knn))

Accuracy: 0.8676328502415459
Precision: 0.7341176470588235
Recall: 0.9285714285714286
F1: 0.8199737187910644


## SVM Model

In [16]:
from sklearn.svm import SVC 
svc = SVC(kernel='linear', random_state=0)  
svc.fit(x_train, y_train)

SVC(kernel='linear', random_state=0)

In [17]:
y_pred_svc = svc.predict(x_test)
y_pred_svc

array([0, 0, 0, ..., 1, 0, 1], dtype=int64)

In [18]:
cm = confusion_matrix(y_test, y_pred_svc)
cm

array([[685,  14],
       [ 44, 292]], dtype=int64)

In [21]:
print("Accuracy:",accuracy_score(y_test, y_pred_svc))
print("Precision:",precision_score(y_test, y_pred_svc))
print("Recall:",recall_score(y_test, y_pred_svc))
print("F1:",f1_score(y_test, y_pred_svc))

Accuracy: 0.9439613526570049
Precision: 0.954248366013072
Recall: 0.8690476190476191
F1: 0.909657320872274


## Conclusion

Upon analysis, SVM model performs better in terms of both accuracy and F1 scores. 